[bar.default]
background_opacity = 0.47999998927116394
capsule_thickness = 0.61999998986721038
end = [ "network", "bluetooth", "battery", "control-center" ]
start = [ "workspaces" ]
thickness = 23

[battery]
warning_threshold = 15

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 768.0
    cy = 682.0
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
app_icon_color = "primary"
font_family = "JetBrainsMono Nerd Font"
panel_anchor_bar = "default"

    [shell.launcher]
    categories = false
    compact = true
    show_app_origin_indicator = false
    show_icons = false

[theme]
builtin = "Gruvbox"
community_palette = "Oasis Abyss"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/khuong/Downloads"

    [wallpaper.default]
    path = "/home/khuong/Downloads/wallhaven-og2kq9.jpg"

    [wallpaper.last]
    path = "/home/khuong/Downloads/wallhaven-og2kq9.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/khuong/Downloads/wallhaven-og2kq9.jpg"

[widget.network]
show_label = false

[widget.workspaces]
change_color_on_hover = false
labels_only_when_occupied = true
style = "minimal"
